# Generated by Django 3.2.5 on 2021-07-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingmodel',
            name='good',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meetingmodel',
            name='read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meetingmodel',
            name='readtext',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
